//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Branches = new HashSet<Branch>();
            this.Projects = new HashSet<Project>();
        }
    
        public int Company_id { get; set; }
        public string Company_name { get; set; }
        public string Bussines_type { get; set; }
    
        public virtual ICollection<Branch> Branches { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
