//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_worker
    {
        public Contract_worker()
        {
            this.Contracts = new HashSet<Contract>();
            this.Project_status_report = new HashSet<Project_status_report>();
        }
    
        public int Employee_id { get; set; }
        public string Specialization { get; set; }
    
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Project_status_report> Project_status_report { get; set; }
    }
}
