//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public Contract()
        {
            this.Contract_task = new HashSet<Contract_task>();
        }
    
        public int Contract_id { get; set; }
        public int Employee_id { get; set; }
        public int Project_id { get; set; }
        public Nullable<System.DateTime> Start_date { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
    
        public virtual ICollection<Contract_task> Contract_task { get; set; }
        public virtual Project Project { get; set; }
        public virtual Contract_worker Contract_worker { get; set; }
    }
}
