//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Office_worker = new HashSet<Office_worker>();
        }
    
        public int Department_id { get; set; }
        public string Department_name { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Manager { get; set; }
    
        public virtual ICollection<Office_worker> Office_worker { get; set; }
    }
}
