//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_status_report
    {
        public int Project_id { get; set; }
        public string Registration { get; set; }
        public Nullable<int> Employee_id { get; set; }
        public string Work_hours { get; set; }
        public string Description { get; set; }
        public string Role { get; set; }
        public string Project_status { get; set; }
    
        public virtual Contract_worker Contract_worker { get; set; }
    }
}
